#!/bin/bash 
mvn clean install
docker build -t babtist/smsgenerator:0.0.2 .
docker push babtist/smsgenerator:0.0.2
aws ecs register-task-definition --cli-input-json file://aws-ecs/taskdefinition.json
aws ecs update-service --cluster $1 --service SmsGeneratorService --task-definition Camp1-SmsGeneratorServiceTask 
